[theme]
st.write("ddsefg vftyjnvf gyi ")
backgroundColor = "#1E1E1E" # Changes the main app background
secondaryBackgroundColor = "#2D2D2D" # Changes sidebar and widget backgrounds
textColor = "#FFFFFF" # Changes main text color
primaryColor = "#4B9CD3" # Changes primary accent color
